# -*- coding: utf-8 -*-
"""11-authordetails.png

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BMqI15NMSZRN7Rvwkc8yS1TLvrSw-ytc

**Author:** [Boorlagadda Harshita]

# New SectionData Science is a multi-disciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge and insights from structured and unstructured data.


Here are some of the popular data science languages:
1. Python
2. R
3. SQL
4. Julia
5. Scala

Data Science libraries are essential tools for data manipulation, analysis, and modeling.

Some of the popular data science libraries are:
1. NumPy
2. Pandas
3. Matplotlib
4. Seaborn
5. Scikit-learn
6. TensorFlow
7. PyTorch# New Section

# New Section| Tool | Description |
|---|---|
| Jupyter Notebook | Interactive environment for data science and machine learning |
| RStudio | Integrated development environment for R |
| Git | Version control system |
| GitHub | Platform for hosting and collaborating on code |
| SQL | Language for managing and manipulating relational databases |
| Python | Programming language for data science and machine learning |
| R | Programming language and environment for statistical computing and graphics |

Objectives of Data Science

* **Data Collection:** Gathering relevant data from various sources.
* **Data Cleaning:** Preparing data for analysis by handling missing values, outliers, and inconsistencies.
* **Data Exploration:** Uncovering patterns, trends, and relationships within the data.
* **Data Modeling:** Building statistical or machine learning models to make predictions or classifications.
* **Data Visualization:** Creating visual representations of data to communicate insights effectively.
* **Data Communication:** Presenting findings and insights to stakeholders in a clear and understandable manner.
"""

def minutes_to_hours(minutes):
  hours = minutes / 60
  return hours

total_minutes = 150
hours = minutes_to_hours(total_minutes)
print(f"{total_minutes} minutes is equal to {hours} hours")

